#!/bin/bash
# This script is used to connect using vinagre

#sshpass -p raspberry ssh pi@192.168.178.33
sudo sshpass -p pi ssh pi@192.168.178.33 tightvncserver
sleep 1
#sshpass -p raspberry ssh pi@192.168.178.33 ls
echo "Conexion done!"
vinagre 192.168.178.33:1
exit
