#!/bin/bash
# This script is used to connect using vinagre

IP='192.168.178.33'
LOGFILE=pi.log

echo "$(date +%F):$(date +%T): Connected to pi with tightvncserver$*" >> $LOGFILE
sudo sshpass -p pi ssh pi@$IP tightvncserver
echo "Conexion done!"
sleep 1

vinagre $IP:1
exit
